
spring:
  application:
    name: movies

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    info.developia.showltan.movies: 'DEBUG'
