
server:
  port: 3002

spring:
  application:
    name: tvshows

  datasource:
    url: jdbc:h2:mem:${spring.application.name}db
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  file: logs/${spring.application.name}.log